In [54]:
from sklearn.linear_model import Ridge
import numpy as np 
import pandas as pd 
from sklearn.model_selection import GridSearchCV, train_test_split

In [55]:
df=pd.read_csv('truedata.csv')

In [56]:
df = df.dropna()

In [57]:
TargetVariable=['True Stress']
Predictors=['Strain Rate','Temperature','True Plastic Strain']
 
X=df[Predictors].values
y=df[TargetVariable].values

In [58]:
from sklearn.preprocessing import StandardScaler
PredictorScaler=StandardScaler()
TargetVarScaler=StandardScaler()
 
# Storing the fit object for later reference
PredictorScalerFit=PredictorScaler.fit(X)
TargetVarScalerFit=TargetVarScaler.fit(y)
 
# Generating the standardized values of X and y
X=PredictorScalerFit.transform(X)
y=TargetVarScalerFit.transform(y)

In [59]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test  = train_test_split(X, y, test_size=0.3, random_state=42)

In [33]:
ridge_reg = Ridge()
params_Ridge = {'alpha': [10,1,0.1,0.01,0.001,0.0001,0.00001,0] , "fit_intercept": [True, False], "solver": ['svd', 'cholesky', 'lsqr', 'sparse_cg', 'sag', 'saga']}
Ridge_GS = GridSearchCV(ridge_reg, param_grid=params_Ridge, n_jobs=-1)
Ridge_GS.fit(X_train,y_train)
Ridge_GS.best_params_

KeyboardInterrupt: 

In [8]:
Ridge_GS.best_estimator_

Ridge(alpha=10, solver='saga')

In [60]:
ridgereg = Ridge(alpha=10, solver='saga', fit_intercept= True)

In [61]:
ridgereg.fit(X_train,y_train)

Ridge(alpha=10, solver='saga')

In [62]:
X_train

array([[-0.23269271, -1.17233136, -0.9498127 ],
       [-0.23269271,  0.06299789, -1.02345743],
       [-0.23269271,  0.06299789, -0.53610264],
       ...,
       [-0.23269271,  1.29832714,  1.95843183],
       [ 0.64631283,  0.06299789, -0.62635353],
       [-0.23269271,  1.29832714,  0.49564548]])

In [63]:
y_pred = ridgereg.predict(X_test)

In [64]:
y_pred

array([[-0.67915208],
       [-0.57708046],
       [-0.39578634],
       ...,
       [ 0.16850597],
       [ 1.96957464],
       [-0.51617884]])

In [65]:
y_pred=TargetVarScalerFit.inverse_transform(y_pred)

In [73]:
y_pred = y_pred.reshape(-1)

In [74]:
y_pred

array([ 709.71985237,  725.22512234,  752.7647508 , ...,  838.48402522,
       1112.0768029 ,  734.47643157])

In [75]:
y_test_orig=TargetVarScalerFit.inverse_transform(y_test)

In [76]:
y_test_orig

array([[ 781.83656],
       [ 622.26907],
       [ 694.36165],
       ...,
       [ 740.82561],
       [1152.24326],
       [ 950.02404]])

In [77]:
y_test_orig = y_test_orig.reshape(-1)

In [78]:
y_test_orig

array([ 781.83656,  622.26907,  694.36165, ...,  740.82561, 1152.24326,
        950.02404])

In [79]:
APE=100*(abs(y_test_orig-y_pred)/y_test_orig)

In [80]:
print('The Accuracy of Ridge model is:', np.mean(APE))

The Accuracy of Ridge model is: 11.789108074667423


In [81]:
MAE=(abs(y_test_orig-y_pred))
print('The Accuracy of Ridge model is:',np.mean(MAE))

The Accuracy of Ridge model is: 96.12474333749077


In [83]:
import statistics
var = (statistics.variance(y_pred))
print(var)
chi_sq = np.sum(((y_test_orig-y_pred)**2)/var)
red_chi_sq = chi_sq/5074
print('The reduced chi squared value for Ridge is', red_chi_sq)

10649.187929705813
The reduced chi squared value for Ridge is 11.209616424621574


# Validating the model

In [21]:
dfvalid=pd.read_csv('150Cvalidationdata.csv')

In [22]:
TargetVariable=['True Stress']
Predictors=['Strain Rate','Temperature','True Plastic Strain']
X_valid=dfvalid[Predictors].values

In [23]:
X_valid

array([[1.0000000e-03, 1.5000000e+02, 6.1896600e-05],
       [1.0000000e-03, 1.5000000e+02, 5.2687700e-05],
       [1.0000000e-03, 1.5000000e+02, 6.9798000e-05],
       ...,
       [1.0000000e-03, 1.5000000e+02, 9.4723457e-02],
       [1.0000000e-03, 1.5000000e+02, 9.4695481e-02],
       [1.0000000e-03, 1.5000000e+02, 9.4743924e-02]])

In [24]:
from sklearn.preprocessing import StandardScaler
PredictorScaler=StandardScaler()
TargetVarScaler=StandardScaler()
 
# Storing the fit object for later reference
PredictorScalerFit=PredictorScaler.fit(X_valid)

# Generating the standardized values of X and y
X_valid=PredictorScalerFit.transform(X_valid)

In [25]:
X_valid

array([[-2.16840434e-19,  0.00000000e+00, -1.75357910e+00],
       [-2.16840434e-19,  0.00000000e+00, -1.75391619e+00],
       [-2.16840434e-19,  0.00000000e+00, -1.75328986e+00],
       ...,
       [-2.16840434e-19,  0.00000000e+00,  1.71155471e+00],
       [-2.16840434e-19,  0.00000000e+00,  1.71053064e+00],
       [-2.16840434e-19,  0.00000000e+00,  1.71230392e+00]])

In [26]:
y_pred_valid = ridgereg.predict(X_valid)

In [27]:
y_pred_valid

array([[-1.18326085],
       [-1.18348857],
       [-1.18306546],
       ...,
       [ 1.15756744],
       [ 1.15687564],
       [ 1.15807356]])

In [28]:
y_pred_valid = y_pred_valid.reshape(-1,1)

In [29]:
y_pred_valid

array([[-1.18326085],
       [-1.18348857],
       [-1.18306546],
       ...,
       [ 1.15756744],
       [ 1.15687564],
       [ 1.15807356]])

In [30]:
y_pred_valid = TargetVarScalerFit.inverse_transform(y_pred_valid)

In [31]:
y_pred_valid

array([[633.14280605],
       [633.10821387],
       [633.17248677],
       ...,
       [988.7281998 ],
       [988.62311114],
       [988.80508176]])

In [32]:
import pandas as pd 
pd.DataFrame(y_pred_valid).to_csv("ridgevalidationpredicteddata.csv")